{
 "title": "ethtool",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "node_netstat_TcpExt_TCPOFOQueue",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg by(instance) (rate(node_netstat_TcpExt_TCPOFOQueue[1m])) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "container_network_receive_packets_dropped_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "avg by(node,pod) (rate(container_network_receive_packets_dropped_total{}[$__rate_interval])) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "container_network_transmit_packets_dropped_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "avg by(node,pod) (rate(container_network_transmit_packets_dropped_total{}[$__rate_interval])) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "container_network_receive_bytes_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "avg by(namespace,pod) (rate(container_network_receive_bytes_total{}[$__rate_interval])) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "container_network_transmit_bytes_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "avg by(namespace,pod) (rate(container_network_transmit_bytes_total{}[$__rate_interval])) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "node_ethtool_bw_in/out/linklocal_allowance_exceeded",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "avg by(instance,device) (rate(node_ethtool_bw_out_allowance_exceeded[$__rate_interval]))",
     "legendFormat": "out {{instance}}/{{device}}"
    },
    {
     "expr": "avg by(instance,device) (rate(node_ethtool_bw_in_allowance_exceeded[$__rate_interval]))",
     "legendFormat": "in {{instance}}/{{device}}"
    },
    {
     "expr": "avg by(instance,device) (rate(node_ethtool_linklocal_allowance_exceeded{}[$__rate_interval]))",
     "legendFormat": "linklocal {{instance}}/{{device}}"
    }
   ]
  }
 ]
}