{
 "title": "Kubernetes / Compute Resources / Cluster Capacity",
 "tags": [
  "jfcoz",
  "kubernetes",
  "capacity"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30m",
 "templating": {
  "list": [
   { "name": "node", "query": { "query": "label_values(node)" } }
  ]
 },
 "panels": [
  { "title": "Nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pods capacity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum (kube_pod_info{node=~\"$node\"})",
     "legendFormat": "Pods"
    },
    {
     "expr": "sum (kube_node_status_allocatable{resource=\"pods\",node=~\"$node\"})",
     "legendFormat": "Pods capacity"
    },
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"pods\",node=~\"$node\"})\n*\n(\n    sum(kube_node_status_condition{condition=\"Ready\",node=~\"$node\"})\n    -\n    1\n)\n/\nsum(kube_node_status_condition{condition=\"Ready\",node=~\"$node\"})",
     "legendFormat": "Pods capacity minus one node"
    }
   ]
  },
  {
   "title": "Nodes count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    { "expr": "count(kube_node_info)", "legendFormat": "Total" }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "CPU allocatable usage",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(node) (rate(container_cpu_usage_seconds_total{image!=\"\",node=~\"$node\"}[5m]) * on (namespace,pod) group_left(phase) (kube_pod_status_phase{phase=~\"^(Pending|Running|Terminating)$\"} == 1))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (node) (kube_pod_container_resource_requests{resource=\"cpu\",node=~\"$node\"} * on (namespace,pod) group_left(phase) (kube_pod_status_phase{phase=~\"^(Pending|Running|Terminating)$\"} == 1))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(node) (kube_node_status_allocatable{resource=\"cpu\",node=~\"$node\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Capacity",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity{resource=\"cpu\",node=~\"$node\"})",
     "legendFormat": "CPU capacity"
    },
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"cpu\",node=~\"$node\"})",
     "legendFormat": "CPU allocatable"
    },
    {
     "expr": "sum (\n    sum by (namespace,pod) (kube_pod_container_resource_requests{resource=\"cpu\",node=~\"$node\"})\n    * on(namespace, pod) group_left() max by (namespace, pod) (\n        kube_pod_status_phase{phase=~\"Pending|Running\"} == 1\n    )\n)",
     "legendFormat": "CPU requests"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\",node=~\"$node\"}[5m]))",
     "legendFormat": "CPU usage"
    },
    {
     "expr": "sum (\n    sum by (namespace,pod) (kube_pod_container_resource_requests{resource=\"cpu\",node=~\"$node\"})\n    * on(namespace, pod) group_left() max by (namespace, pod) (\n        kube_pod_status_phase{phase=~\"Pending|Running\"} == 1\n    )\n)\n- sum(rate(container_cpu_usage_seconds_total{image!=\"\",node=~\"$node\"}[5m]))",
     "legendFormat": "CPU waste"
    },
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"cpu\",node=~\"$node\"})\n*\n(\n    sum(kube_node_status_condition{condition=\"Ready\",node=~\"$node\"})\n    -\n    1\n)\n/\nsum(kube_node_status_condition{condition=\"Ready\",node=~\"$node\"})",
     "legendFormat": "CPU allocatable minus one node"
    }
   ]
  },
  {
   "title": "cpu waste",
   "type": "timeseries",
   "description": "reservation over usage",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "avg by (namespace,pod) (kube_pod_container_resource_requests{resource=\"cpu\",node=~\"$node\"})\n-\navg by (namespace,pod) (rate(container_cpu_usage_seconds_total{image!=\"\",node=~\"$node\"}[5m]))\n> 0",
     "legendFormat": "{{namespace}}/{{pod}}"
    }
   ]
  },
  {
   "title": "Top CPU under reservation / daily average",
   "type": "bargauge",
   "description": "CPU request is less than the average daily usage, and at least 10m under-reservation",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "core" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(20,\n(\n    avg by (namespace, pod, container) (avg_over_time(rate(container_cpu_usage_seconds_total{image!=\"\"}[1m])[1d:]))\n    -\n    avg by (namespace, pod, container) (kube_pod_container_resource_requests{resource=\"cpu\"})\n    > 0.010\n)\nand\n(\n    avg by (namespace, pod, container) (kube_pod_container_resource_requests{resource=\"cpu\"})\n    > 0\n)\nand\n(\n    avg by (namespace, pod, container) (avg_over_time(rate(container_cpu_usage_seconds_total{image!=\"\"}[1m])[1d:]))\n    /\n    avg by (namespace, pod, container) (kube_pod_container_resource_requests{resource=\"cpu\"})\n    > 1\n)\n)",
     "legendFormat": "{{namespace}}/{{container}}@{{pod}}"
    }
   ]
  },
  {
   "title": "Top CPU over reservation / daily 99 percentile",
   "type": "bargauge",
   "description": "CPU request is more than twice the 99 percentile daily usage, and at least 10m over-reservation",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "core" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(20,\n(\n    avg by (namespace, pod, container) (kube_pod_container_resource_requests{resource=\"cpu\"})\n    -\n    avg by (namespace, pod, container) (quantile_over_time(0.99,rate(container_cpu_usage_seconds_total{image!=\"\",container!=\"\"}[1m])[1d:]))\n    > 0.01\n) and (\n    avg by (namespace, pod, container) (quantile_over_time(0.99,rate(container_cpu_usage_seconds_total{image!=\"\",container!=\"\"}[1m])[1d:]))\n    /\n    avg by (namespace, pod, container) (kube_pod_container_resource_requests{resource=\"cpu\"})\n    < 1\n)\n)",
     "legendFormat": "{{namespace}}/{{container}}@{{pod}}"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Memory allocatable usage",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(node,type) (\n    label_replace(\n        sum by(node) (container_memory_working_set_bytes{container!=\"\",node=~\"$node\"} @ end() * on (namespace,pod) group_left(phase) (kube_pod_status_phase{phase=~\"^(Pending|Running|Terminating)$\"} == 1))\n        ,\"type\",\"usage\",\"node\",\".*\"\n    )\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(node,type) (\n    label_replace(\n        sum by (node) (kube_pod_container_resource_requests{resource=\"memory\",node=~\"$node\"} * on (namespace,pod) group_left(phase) (kube_pod_status_phase{phase=~\"^(Pending|Running|Terminating)$\"} == 1))\n        ,\"type\",\"request\",\"node\",\".*\"\n    )\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(node,type) (\n    label_replace(\n        sum by(node) (kube_node_status_allocatable{resource=\"memory\",node=~\"$node\"} @ end())\n        ,\"type\",\"allocatable\",\"node\",\".*\"\n    )\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg by(node) (\n    avg by(internal_ip) (\n        label_replace(\n            avg by(instance) (\n                node_memory_MemFree_bytes{node=~\"$node\"}\n            ),\n            \"internal_ip\",\n            \"$1\",\n            \"instance\",\n            \"([^:]+):.*\"\n        )\n    )\n    * on(internal_ip) group_right\n    kube_node_info{node=~\"$node\"}\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg by(node) (\n    avg by(internal_ip) (\n        label_replace(\n            avg by(instance) (\n                node_memory_Cached_bytes{node=~\"$node\"}\n            ),\n            \"internal_ip\",\n            \"$1\",\n            \"instance\",\n            \"([^:]+):.*\"\n        )\n    )\n    * on(internal_ip) group_right\n    kube_node_info{node=~\"$node\"}\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg by(node) (\n    avg by(internal_ip) (\n        label_replace(\n            avg by(instance) (\n                node_memory_MemFree_bytes{node=~\"$node\"} + node_memory_Cached_bytes{node=~\"$node\"}\n            ),\n            \"internal_ip\",\n            \"$1\",\n            \"instance\",\n            \"([^:]+):.*\"\n        )\n    )\n    * on(internal_ip) group_right\n    kube_node_info{node=~\"$node\"}\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg by(node) (\n    avg by(internal_ip) (\n        label_replace(\n            avg by(instance) (\n                node_memory_Buffers_bytes{node=~\"$node\"}\n            ),\n            \"internal_ip\",\n            \"$1\",\n            \"instance\",\n            \"([^:]+):.*\"\n        )\n    )\n    * on(internal_ip) group_right\n    kube_node_info{node=~\"$node\"}\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory capacity",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum (kube_node_status_capacity{resource=\"memory\",node=~\"$node\"})",
     "legendFormat": "Mem capacity"
    },
    {
     "expr": "sum (kube_node_status_allocatable{resource=\"memory\",node=~\"$node\"})",
     "legendFormat": "Mem allocatable"
    },
    {
     "expr": "sum (\n    sum by (namespace,pod) (kube_pod_container_resource_requests{resource=\"memory\",node=~\"$node\"})\n    * on(namespace, pod) group_left() max by (namespace, pod) (\n        kube_pod_status_phase{phase=~\"Pending|Running\"} == 1\n    )\n)",
     "legendFormat": "Mem request"
    },
    {
     "expr": "sum (\n    sum by (namespace,pod) (kube_pod_container_resource_limits{resource=\"memory\",node=~\"$node\"})\n    * on(namespace, pod) group_left() max by (namespace, pod) (\n        kube_pod_status_phase{phase=~\"Pending|Running\"} == 1\n    )\n)",
     "legendFormat": "Mem limit"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{container!=\"\",node=~\"$node\"})",
     "legendFormat": "Mem usage"
    },
    {
     "expr": "sum (kube_node_status_allocatable{resource=\"memory\",node=~\"$node\"})\n-\nsum (\n    sum by (namespace,pod) (kube_pod_container_resource_requests{resource=\"memory\",node=~\"$node\"})\n    * on(namespace, pod) group_left() max by (namespace, pod) (\n        kube_pod_status_phase{phase=~\"Pending|Running\"} == 1\n    )\n)",
     "legendFormat": "mem remaining"
    },
    {
     "expr": "sum (\n    sum by (namespace,pod) (kube_pod_container_resource_requests{resource=\"memory\",node=~\"$node\"})\n    * on(namespace, pod) group_left() max by (namespace, pod) (\n        kube_pod_status_phase{phase=~\"Pending|Running\"} == 1\n    )\n)\n-\nsum (container_memory_working_set_bytes{container!=\"\",node=~\"$node\"})",
     "legendFormat": "Memory waste"
    },
    {
     "expr": "sum(kube_node_status_allocatable{resource=\"memory\",node=~\"$node\"})\n*\n(\n    sum(kube_node_status_condition{condition=\"Ready\",node=~\"$node\"})\n    -\n    1\n)\n/\nsum(kube_node_status_condition{condition=\"Ready\",node=~\"$node\"})",
     "legendFormat": "Mem allocatable minus one node"
    }
   ]
  },
  {
   "title": "Memory waste",
   "type": "timeseries",
   "description": "reservation over usage",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg by (namespace,pod) (kube_pod_container_resource_requests{resource=\"memory\",node=~\"$node\"})\n-\navg by (namespace,pod) (container_memory_working_set_bytes{container!=\"\",node=~\"$node\"})\n> 0",
     "legendFormat": "{{namespace}}/{{pod}}"
    }
   ]
  },
  {
   "title": "Top memory under reservation / daily average",
   "type": "bargauge",
   "description": "memory request is less than the average daily usage, and at least 10MB under-reservation",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(20,\n(\n    avg by (namespace, pod, container) (max_over_time(container_memory_working_set_bytes{image!=\"\",container!=\"\"}[1d:]))\n    -\n    avg by (namespace, pod, container) (kube_pod_container_resource_requests{resource=\"memory\"})\n    > 0.010\n)\nand\n(\n    avg by (namespace, pod, container) (kube_pod_container_resource_requests{resource=\"memory\"})\n    > 0\n)\nand\n(\n    avg by (namespace, pod, container) (max_over_time(container_memory_working_set_bytes{image!=\"\",container!=\"\"}[1d:]))\n    /\n    avg by (namespace, pod, container) (kube_pod_container_resource_requests{resource=\"memory\"})\n    > 1\n)\n)",
     "legendFormat": "{{namespace}}/{{container}}@{{pod}}"
    }
   ]
  },
  {
   "title": "Top Memory over reservation / daily percentile",
   "type": "bargauge",
   "description": "Memory request is more than max daily usage, and at least 10Mb over-reservation",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(20,\n(\n    avg by (namespace, pod, container) (kube_pod_container_resource_requests{resource=\"memory\"})\n    -\n    avg by (namespace, pod, container) (max_over_time(container_memory_working_set_bytes{image!=\"\",container!=\"\"}[1d:]))\n    > 10*1024*1024\n) and (\n    avg by (namespace, pod, container) (max_over_time(container_memory_working_set_bytes{image!=\"\",container!=\"\"}[1d:]))\n    /\n    avg by (namespace, pod, container) (kube_pod_container_resource_requests{resource=\"memory\"})\n    < 1\n)\n)",
     "legendFormat": "{{namespace}}/{{container}}@{{pod}}"
    }
   ]
  },
  {
   "title": "Memory usage over request",
   "type": "timeseries",
   "description": "containers using more memory than requested are at risk of eviction",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "(\n    (\n        sum by(container, namespace, pod) (container_memory_working_set_bytes{node=~\"$node\",container!=\"\"})\n        -\n        sum by(container, namespace, pod) (kube_pod_container_resource_requests{resource=\"memory\",node=~\"$node\"})\n    )\n    or\n    (\n        sum by(container, namespace, pod) (container_memory_working_set_bytes{node=~\"$node\",container!=\"\"})\n    )\n) > 0 * 1024 * 1024",
     "legendFormat": "{{namespace}}/{{pod}}/{{container}}"
    }
   ]
  }
 ]
}