{
 "title": "Postgresql Table stats",
 "tags": [
  "jfcoz",
  "postgresql"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "schemaname", "query": { "query": "label_values(schemaname)" } },
   {
    "name": "relname",
    "query": {
     "query": "label_values({schemaname=\"$schemaname\"},relname)"
    }
   },
   { "name": "count", "query": "5,10,15,20" }
  ]
 },
 "panels": [
  {
   "title": "Table size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg by(schemaname,relname) (pg_stat_user_tables_table_size_bytes{schemaname=~\"$schemaname\",relname=~\"$relname\"})",
     "legendFormat": "{{relname}}"
    }
   ]
  },
  {
   "title": "Index size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg by(schemaname,relname) (pg_stat_user_tables_index_size_bytes{schemaname=~\"$schemaname\",relname=~\"$relname\"})",
     "legendFormat": "{{relname}}"
    }
   ]
  },
  { "title": "Table size", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  { "title": "Table maintenance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "live/dead tuples",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "avg by(schemaname,relname) (pg_stat_user_tables_n_live_tup{schemaname=~\"$schemaname\",relname=~\"$relname\"})",
     "legendFormat": "{{relname}} live"
    },
    {
     "expr": "avg by(schemaname,relname) (pg_stat_user_tables_n_dead_tup{schemaname=~\"$schemaname\",relname=~\"$relname\"})",
     "legendFormat": "{{relname}} dead"
    }
   ]
  },
  {
   "title": "dead tuples",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "avg by(schemaname,relname) (pg_stat_user_tables_n_dead_tup{schemaname=~\"$schemaname\",relname=~\"$relname\"})",
     "legendFormat": "{{relname}} dead"
    }
   ]
  },
  {
   "title": "Top Autovacuum count per hour",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "topk(\n  $count,\n  avg by(schemaname,relname) (delta(pg_stat_user_tables_autovacuum_count{schemaname=~\"$schemaname\",relname=~\"$relname\"}[1h]))\n)",
     "legendFormat": "{{relname}}"
    }
   ]
  },
  {
   "title": "Time since last autovacuum",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by(schemaname,relname) (\n    timestamp(pg_stat_user_tables_last_autovacuum{schemaname=~\"$schemaname\",relname=~\"$relname\"})\n    -\n    pg_stat_user_tables_last_autovacuum{schemaname=~\"$schemaname\",relname=~\"$relname\"}\n) < 365*24*60*60",
     "legendFormat": "{{relname}}"
    }
   ]
  },
  { "title": "row activity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "insert/update/delete",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "avg by(schemaname,relname) (rate(pg_stat_user_tables_n_tup_upd{schemaname=~\"$schemaname\",relname=~\"$relname\"}[$__rate_interval]))",
     "legendFormat": "{{relname}} update"
    },
    {
     "expr": "avg by(schemaname,relname) (rate(pg_stat_user_tables_n_tup_ins{schemaname=~\"$schemaname\",relname=~\"$relname\"}[$__rate_interval]))",
     "legendFormat": "{{relname}} insert"
    },
    {
     "expr": "avg by(schemaname,relname) (rate(pg_stat_user_tables_n_tup_del{schemaname=~\"$schemaname\",relname=~\"$relname\"}[$__rate_interval]))",
     "legendFormat": "{{relname}} delete"
    }
   ]
  },
  {
   "title": "HOT update ratio",
   "type": "timeseries",
   "description": "When fillfactor is suffisent and updated column is not indexed, data can be updated in the same block without index update, this reduce IOPS",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "topk(\n    $count,\n    avg by(schemaname,relname) (\n        rate(pg_stat_user_tables_n_tup_hot_upd{schemaname=~\"$schemaname\",relname=~\"$relname\"}[$__rate_interval])\n        /\n        rate(pg_stat_user_tables_n_tup_upd{schemaname=~\"$schemaname\",relname=~\"$relname\"}[$__rate_interval])\n    )\n)",
     "legendFormat": "{{relname}}"
    }
   ]
  },
  {
   "title": "non-HOT update load",
   "type": "timeseries",
   "description": "Total non-HOT update count by table. Theses update also need to maintain all indexes and makes IOPS",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "topk(\n    $count,\n    avg by(schemaname,relname) (\n        rate(pg_stat_user_tables_n_tup_upd{schemaname=~\"$schemaname\",relname=~\"$relname\"}[$__rate_interval])\n        -\n        rate(pg_stat_user_tables_n_tup_hot_upd{schemaname=~\"$schemaname\",relname=~\"$relname\"}[$__rate_interval])\n    )\n)",
     "legendFormat": "{{relname}}"
    }
   ]
  },
  { "title": "Table hit/miss", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "pg_statio_user_tables_heap_blocks_hit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "topk($count,sum by(schemaname,relname) (rate(pg_statio_user_tables_heap_blocks_hit{schemaname=~\"$schemaname\",relname=~\"$relname\"}[$__rate_interval])))",
     "legendFormat": "{{relname}}"
    }
   ]
  },
  {
   "title": "pg_statio_user_tables_heap_blocks_read",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "targets": [
    {
     "expr": "topk($count,sum by(schemaname,relname) (rate(pg_statio_user_tables_heap_blocks_read{schemaname=~\"$schemaname\",relname=~\"$relname\"}[$__rate_interval])))",
     "legendFormat": "{{relname}}"
    }
   ]
  },
  {
   "title": "pg_statio_user_tables_heap_blocks hit rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "topk($count,\nsum by(schemaname,relname) (\n    rate(pg_statio_user_tables_heap_blocks_hit{schemaname=~\"$schemaname\",relname=~\"$relname\"}[$__rate_interval])\n    /\n    (\n        rate(pg_statio_user_tables_heap_blocks_hit{schemaname=~\"$schemaname\",relname=~\"$relname\"}[$__rate_interval])\n        +\n        rate(pg_statio_user_tables_heap_blocks_read{schemaname=~\"$schemaname\",relname=~\"$relname\"}[$__rate_interval])\n    )\n)\n)",
     "legendFormat": "{{relname}}"
    }
   ]
  },
  { "title": "Index hit/miss", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "pg_statio_user_indexes_idx_blks_hit_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "targets": [
    {
     "expr": "topk($count,sum by(schemaname,relname,indexrelname) (rate(pg_statio_user_indexes_idx_blks_hit_total{schemaname=~\"$schemaname\",relname=~\"$relname\"}[$__rate_interval])))",
     "legendFormat": "{{relname}}/{{indexrelname}}"
    }
   ]
  },
  {
   "title": "pg_statio_user_indexes_idx_blks_read_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
   "targets": [
    {
     "expr": "topk($count,sum by(schemaname,relname,indexrelname) (rate(pg_statio_user_indexes_idx_blks_read_total{schemaname=~\"$schemaname\",relname=~\"$relname\"}[$__rate_interval])))",
     "legendFormat": "{{relname}}/{{indexrelname}}"
    }
   ]
  },
  {
   "title": "pg_statio_user_indexes_idx_blks hit rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "topk($count,\nsum by(schemaname,relname,indexrelname) (\n    rate(pg_statio_user_indexes_idx_blks_hit_total{schemaname=~\"$schemaname\",relname=~\"$relname\"}[$__rate_interval])\n    /\n    (\n        rate(pg_statio_user_indexes_idx_blks_hit_total{schemaname=~\"$schemaname\",relname=~\"$relname\"}[$__rate_interval])\n        +\n        rate(pg_statio_user_indexes_idx_blks_read_total{schemaname=~\"$schemaname\",relname=~\"$relname\"}[$__rate_interval])\n    )\n)\n)",
     "legendFormat": "{{relname}}/{{indexrelname}}"
    }
   ]
  },
  {
   "title": "Index tup fetch",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg by(schemaname,relname) (rate(pg_stat_user_tables_idx_tup_fetch{schemaname=~\"$schemaname\",relname=~\"$relname\"}[$__rate_interval]))",
     "legendFormat": "{{relname}} tup fetch"
    }
   ]
  },
  {
   "title": "Index tup fetch VS autovacuum",
   "type": "timeseries",
   "description": "table block read to check visibility of rows. Vacuuming more often reduce tup fetch",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg by(schemaname,relname) (rate(pg_stat_user_tables_idx_tup_fetch{schemaname=~\"$schemaname\",relname=~\"$relname\"}[$__rate_interval]))",
     "legendFormat": "{{relname}} tup fetch"
    },
    {
     "expr": "avg by(schemaname,relname) (\n    timestamp(pg_stat_user_tables_last_autovacuum{schemaname=~\"$schemaname\",relname=~\"$relname\"})\n    -\n    pg_stat_user_tables_last_autovacuum{schemaname=~\"$schemaname\",relname=~\"$relname\"}\n)",
     "legendFormat": "{{relname}} autovacuum"
    }
   ]
  }
 ]
}