{
 "title": "Trivy / Image scan",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30m",
 "templating": {
  "list": [
   { "name": "namespace", "query": { "query": "label_values(namespace)" } },
   { "name": "severity", "query": { "query": "label_values(severity)" } }
  ]
 },
 "panels": [
  {
   "title": "Critical",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (\nmax by(namespace,image) (\nkube_pod_container_info{namespace=~\"$namespace\"}\nor\nkube_pod_init_container_info{namespace=~\"$namespace\"}\n)\n* on(namespace,image) group_right()\nmax by(namespace,image,severity) (\n    label_join(\n        label_join(\n            label_replace(\n                trivy_image_vulnerabilities{severity=\"Critical\"} > 0,\n                \"image_registry\",\n                \"$1\",\n                \"image_registry\",\n                \"index\\\\.(docker\\\\.io)\"\n            ),\n            \"registry_repository\",\n            \"/\",\n            \"image_registry\",\n            \"image_repository\"\n        ),\n        \"image\",\n        \":\",\n        \"registry_repository\",\n        \"image_tag\"\n    )\n)\n)\nor vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "High",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (\n    max by(namespace,image) (\n    kube_pod_container_info{namespace=~\"$namespace\"}\n    or\n    kube_pod_init_container_info{namespace=~\"$namespace\"}\n    )\n    * on(namespace,image) group_right()\n    max by(namespace,image,severity) (\n        label_join(\n            label_join(\n                label_replace(\n                    trivy_image_vulnerabilities{severity=\"High\"} > 0,\n                    \"image_registry\",\n                    \"$1\",\n                    \"image_registry\",\n                    \"index\\\\.(docker\\\\.io)\"\n                ),\n                \"registry_repository\",\n                \"/\",\n                \"image_registry\",\n                \"image_repository\"\n            ),\n            \"image\",\n            \":\",\n            \"registry_repository\",\n            \"image_tag\"\n        )\n    )\n)\nor vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Medium",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (\n    max by(namespace,image) (\n    kube_pod_container_info{namespace=~\"$namespace\"}\n    or\n    kube_pod_init_container_info{namespace=~\"$namespace\"}\n    )\n    * on(namespace,image) group_right()\n    max by(namespace,image,severity) (\n        label_join(\n            label_join(\n                label_replace(\n                    trivy_image_vulnerabilities{severity=\"Medium\"} > 0,\n                    \"image_registry\",\n                    \"$1\",\n                    \"image_registry\",\n                    \"index\\\\.(docker\\\\.io)\"\n                ),\n                \"registry_repository\",\n                \"/\",\n                \"image_registry\",\n                \"image_repository\"\n            ),\n            \"image\",\n            \":\",\n            \"registry_repository\",\n            \"image_tag\"\n        )\n    )\n)\nor vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Low",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (\n    max by(namespace,image) (\n    kube_pod_container_info{namespace=~\"$namespace\"}\n    or\n    kube_pod_init_container_info{namespace=~\"$namespace\"}\n    )\n    * on(namespace,image) group_right()\n    max by(namespace,image,severity) (\n        label_join(\n            label_join(\n                label_replace(\n                    trivy_image_vulnerabilities{severity=\"Low\"} > 0,\n                    \"image_registry\",\n                    \"$1\",\n                    \"image_registry\",\n                    \"index\\\\.(docker\\\\.io)\"\n                ),\n                \"registry_repository\",\n                \"/\",\n                \"image_registry\",\n                \"image_repository\"\n            ),\n            \"image\",\n            \":\",\n            \"registry_repository\",\n            \"image_tag\"\n        )\n    )\n)\nor vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Unknown",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (\n    max by(namespace,image) (\n    kube_pod_container_info{namespace=~\"$namespace\"}\n    or\n    kube_pod_init_container_info{namespace=~\"$namespace\"}\n    )\n    * on(namespace,image) group_right()\n    max by(namespace,image,severity) (\n        label_join(\n            label_join(\n                label_replace(\n                    trivy_image_vulnerabilities{severity=\"Unknown\"} > 0,\n                    \"image_registry\",\n                    \"$1\",\n                    \"image_registry\",\n                    \"index\\\\.(docker\\\\.io)\"\n                ),\n                \"registry_repository\",\n                \"/\",\n                \"image_registry\",\n                \"image_repository\"\n            ),\n            \"image\",\n            \":\",\n            \"registry_repository\",\n            \"image_tag\"\n        )\n    )\n)\nor vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (\n    max by(namespace,image) (\n    kube_pod_container_info{namespace=~\"$namespace\"}\n    or\n    kube_pod_init_container_info{namespace=~\"$namespace\"}\n    )\n    * on(namespace,image) group_right()\n    max by(namespace,image,severity) (\n        label_join(\n            label_join(\n                label_replace(\n                    trivy_image_vulnerabilities{} > 0,\n                    \"image_registry\",\n                    \"$1\",\n                    \"image_registry\",\n                    \"index\\\\.(docker\\\\.io)\"\n                ),\n                \"registry_repository\",\n                \"/\",\n                \"image_registry\",\n                \"image_repository\"\n            ),\n            \"image\",\n            \":\",\n            \"registry_repository\",\n            \"image_tag\"\n        )\n    )\n)\nor vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Used image vulnerabilities",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "max by(namespace,image) (\n    kube_pod_container_info{namespace=~\"$namespace\"}\n    or\n    kube_pod_init_container_info{namespace=~\"$namespace\"}\n)\n* on(namespace,image) group_right()\nmax by(namespace,image,severity) (\n    label_join(\n        label_join(\n            label_replace(\n                trivy_image_vulnerabilities{severity=~\"$severity\"} > 0,\n                \"image_registry\",\n                \"$1\",\n                \"image_registry\",\n                \"index\\\\.(docker\\\\.io)\"\n            ),\n            \"registry_repository\",\n            \"/\",\n            \"image_registry\",\n            \"image_repository\"\n        ),\n        \"image\",\n        \":\",\n        \"registry_repository\",\n        \"image_tag\"\n    )\n)",
     "legendFormat": "{{namespace}} {{image}} {{severity}}"
    }
   ]
  },
  {
   "title": "Used image vulnerabilities by namespace",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "max by(namespace) (\n    max by(namespace,image) (\n        kube_pod_container_info{namespace=~\"$namespace\"}\n        or\n        kube_pod_init_container_info{namespace=~\"$namespace\"}\n    )\n    * on(namespace,image) group_right()\n    max by(namespace,image,severity) (\n        label_join(\n            label_join(\n                label_replace(\n                    trivy_image_vulnerabilities{severity=~\"$severity\"} > 0,\n                    \"image_registry\",\n                    \"$1\",\n                    \"image_registry\",\n                    \"index\\\\.(docker\\\\.io)\"\n                ),\n                \"registry_repository\",\n                \"/\",\n                \"image_registry\",\n                \"image_repository\"\n            ),\n            \"image\",\n            \":\",\n            \"registry_repository\",\n            \"image_tag\"\n        )\n    )\n)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Used image CVE",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "max by (vuln_id) (\n    trivy_vulnerability_id{namespace=~\"$namespace\",severity=~\"$severity\"}\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}