{
 "title": "Varnish (kube-httpcache)",
 "tags": [
  "jfcoz",
  "varnish",
  "kubernetes",
  "kube-httpcache"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(varnish_backend_conn,namespace)"
    }
   },
   {
    "name": "service",
    "query": {
     "query": "label_values(varnish_backend_conn{namespace=\"$namespace\"},service)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(varnish_backend_conn{namespace=\"$namespace\", service=\"$service\"},pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Pod resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Metrics documentation",
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": {
    "content": "https://varnish-cache.org/docs/trunk/reference/varnish-counters.html#varnish-counters-7"
   }
  },
  {
   "title": "sc_* (except rx/tx)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "avg by(pod) (rate(varnish_main_sc_overload{namespace=\"$namespace\",service=\"$service\",pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "{{pod}} sc_overload"
    },
    {
     "expr": "avg by(pod) (rate(varnish_main_sc_pipe_overflow{namespace=\"$namespace\",service=\"$service\",pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "{{pod}} sc_pipe_overflow"
    },
    {
     "expr": "avg by(pod) (rate(varnish_main_sc_range_short{namespace=\"$namespace\",service=\"$service\",pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "{{pod}} sc_range_short"
    },
    {
     "expr": "avg by(pod) (rate(varnish_main_sc_rem_close{namespace=\"$namespace\",service=\"$service\",pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "{{pod}} sc_rem_close"
    },
    {
     "expr": "avg by(pod) (rate(varnish_main_sc_req_close{namespace=\"$namespace\",service=\"$service\",pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "{{pod}} sc_req_close"
    },
    {
     "expr": "avg by(pod) (rate(varnish_main_sc_req_http10{namespace=\"$namespace\",service=\"$service\",pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "{{pod}} sc_req_http10"
    },
    {
     "expr": "avg by(pod) (rate(varnish_main_sc_req_http20{namespace=\"$namespace\",service=\"$service\",pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "{{pod}} sc_req_http20"
    },
    {
     "expr": "avg by(pod) (rate(varnish_main_sc_resp_close{namespace=\"$namespace\",service=\"$service\",pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "{{pod}} sc_resp_close"
    },
    {
     "expr": "avg by(pod) (rate(varnish_main_sc_vcl_failure{namespace=\"$namespace\",service=\"$service\",pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "{{pod}} sc_vcl_failure"
    }
   ]
  },
  {
   "title": "Memory RSS vs request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "kube_pod_container_resource_requests{namespace=~\"$namespace\",container=\"varnish\",pod=~\"$service-.*\",resource=\"memory\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "container_memory_rss{namespace=~\"$namespace\",container=\"varnish\",pod=~\"$service-.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage vs request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "targets": [
    {
     "expr": "kube_pod_container_resource_requests{resource=\"cpu\",namespace=~\"$namespace\",container=\"varnish\",pod=~\"$service-.*\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\",container=\"varnish\",pod=~\"$service-.*\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Client connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "sc_rx*",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "avg by(pod) (rate(varnish_main_sc_rx_bad{namespace=\"$namespace\",service=\"$service\",pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "{{pod}} sc_rx_bad"
    },
    {
     "expr": "avg by(pod) (rate(varnish_main_sc_rx_body{namespace=\"$namespace\",service=\"$service\",pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "{{pod}} sc_rx_body"
    },
    {
     "expr": "avg by(pod) (rate(varnish_main_rx_close_idle{namespace=\"$namespace\",service=\"$service\",pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "{{pod}} sc_rx_close_idle"
    },
    {
     "expr": "avg by(pod) (rate(varnish_main_sc_rx_junk{namespace=\"$namespace\",service=\"$service\",pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "{{pod}} sc_rx_junk"
    },
    {
     "expr": "avg by(pod) (rate(varnish_main_sc_rx_overflow{namespace=\"$namespace\",service=\"$service\",pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "{{pod}} sc_rx_overflow"
    },
    {
     "expr": "avg by(pod) (rate(varnish_main_sc_rx_timeout{namespace=\"$namespace\",service=\"$service\",pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "{{pod}} sc_rx_timeout"
    }
   ]
  },
  {
   "title": "sc_tx*",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "avg by(pod) (rate(varnish_main_sc_tx_eof{namespace=\"$namespace\",service=\"$service\",pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "{{pod}} sc_tx_eof"
    },
    {
     "expr": "avg by(pod) (rate(varnish_main_sc_tx_error{namespace=\"$namespace\",service=\"$service\",pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "{{pod}} sc_tx_error"
    },
    {
     "expr": "avg by(pod) (rate(varnish_main_sc_tx_pipe{namespace=\"$namespace\",service=\"$service\",pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "{{pod}} sc_tx_pipe"
    }
   ]
  },
  { "title": "Bans", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Bans added",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "avg by(pod) (rate(varnish_main_bans_added{namespace=\"$namespace\",service=\"$service\",pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bans completed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "avg by(pod) (rate(varnish_main_bans_completed{namespace=\"$namespace\",service=\"$service\",pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Cache performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Hit/HitForPass/HitMiss/Miss",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "avg by (pod) (rate(varnish_main_cache_miss{namespace=\"$namespace\",service=\"$service\",pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "cache_miss {{pod}}"
    },
    {
     "expr": "avg by (pod) (rate(varnish_main_cache_hit{namespace=\"$namespace\",service=\"$service\",pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "cache_hit {{pod}}"
    },
    {
     "expr": "avg by (pod) (rate(varnish_main_cache_hitmiss{namespace=\"$namespace\",service=\"$service\",pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "cache_hitmiss {{pod}}"
    },
    {
     "expr": "avg by (pod) (rate(varnish_main_cache_hitpass{namespace=\"$namespace\",service=\"$service\",pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "cache_hitpass {{pod}}"
    },
    {
     "expr": "avg by (pod) (rate(varnish_main_cache_hit_grace{namespace=\"$namespace\",service=\"$service\",pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "cache_hitgrace {{pod}}"
    }
   ]
  },
  {
   "title": "Hit Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expression": "$cache_hit / ($cache_hit+$cache_miss)",
     "type": "math"
    }
   ]
  },
  {
   "title": "Objects in cache",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "varnish_main_n_object{namespace=\"$namespace\",service=\"$service\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} objects"
    }
   ]
  },
  { "title": "LRU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "LRU Limited",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "targets": [
    {
     "expr": "rate(varnish_main_n_lru_limited{namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\"}[$__rate_interval])",
     "legendFormat": "{{pod}} lru_limited"
    }
   ]
  },
  {
   "title": "LRU Nuked",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "targets": [
    {
     "expr": "rate(varnish_main_n_lru_nuked{namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\"}[$__rate_interval])",
     "legendFormat": "{{pod}} lru_nuked"
    }
   ]
  },
  {
   "title": "LRU Moved",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "targets": [
    {
     "expr": "rate(varnish_main_n_lru_moved{namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\"}[$__rate_interval])",
     "legendFormat": "{{pod}} lru_moved"
    }
   ]
  },
  { "title": "Backend connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 } },
  {
   "title": "Varnish backend requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 70 },
   "targets": [
    {
     "expr": "avg by (pod,backend) (rate(varnish_backend_req{namespace=\"$namespace\",service=\"$service\",pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "{{pod}} to {{backend}}"
    }
   ]
  },
  {
   "title": "Varnish backend connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 70 },
   "targets": [
    {
     "expr": "avg by(pod,backend) (varnish_backend_conn{namespace=\"$namespace\",service=\"$service\",pod=~\"$pod\"})",
     "legendFormat": "{{pod}} to {{backend}}"
    }
   ]
  },
  {
   "title": "Varnish backend fail",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 78 },
   "targets": [
    {
     "expr": "avg by(pod,backend) (rate(varnish_backend_fail{namespace=\"$namespace\",service=\"$service\",pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "fail {{pod}} to {{backend}}"
    },
    {
     "expr": "avg by(pod,backend) (rate(varnish_backend_fail_etimedout{namespace=\"$namespace\",service=\"$service\",pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "fail etimedout {{pod}} to {{backend}}"
    },
    {
     "expr": "avg by(pod,backend) (rate(varnish_backend_fail_eaccess{namespace=\"$namespace\",service=\"$service\",pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "fail eaccess {{pod}} to {{backend}}"
    },
    {
     "expr": "avg by(pod,backend) (rate(varnish_backend_fail_eaddrnotavail{namespace=\"$namespace\",service=\"$service\",pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "fail eaddrnotavail {{pod}} to {{backend}}"
    },
    {
     "expr": "avg by(pod,backend) (rate(varnish_backend_fail_econnrefused{namespace=\"$namespace\",service=\"$service\",pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "fail econnrefused {{pod}} to {{backend}}"
    },
    {
     "expr": "avg by(pod,backend) (rate(varnish_backend_fail_enetunreach{namespace=\"$namespace\",service=\"$service\",pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "fail enetunreach {{pod}} to {{backend}}"
    },
    {
     "expr": "avg by(pod,backend) (rate(varnish_backend_fail_other{namespace=\"$namespace\",service=\"$service\",pod=~\"$pod\"}[$__rate_interval]))",
     "legendFormat": "fail other {{pod}} to {{backend}}"
    }
   ]
  }
 ]
}